// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: ../scanner.flex

import java_cup.runtime.Symbol;

/*
Directivas:
public: classe publica
cup: compatibilidade com cup
full: estende o alfabeto com todos os valores de 8 bits
linha: adicionar a variável int yyline, para indicar a linha do lexema
char: adicionar a variável int yychar, para indicar o índice do primeiro caractere do lexema
ignorecase: validar, independentemente de a letra ser maiúscula ou minúscula
eofval: especifica um valor de retorno no final do arquivo
*/


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  2,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  0,  0,  3,  0,  0,  0,  4,  5,  0,  0,  0,  0,  0,  0, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  0,  7,  0,  0,  0,  0, 
     0,  8,  8,  9, 10,  8,  8,  8,  8,  8,  8,  8,  8, 11, 12, 13, 
     8, 14,  8,  8, 15, 16, 17,  8,  8,  8,  8,  0,  0,  0,  0, 18, 
     0, 19,  8,  9, 10, 20,  8,  8,  8, 21,  8,  8,  8, 11, 22, 23, 
     8, 14, 24,  8, 25, 26, 27,  8,  8,  8,  8,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0, 28, 29,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0, 29,  0,  0,  0,  0, 29,  0,  0,  0,  0,  0, 
    29, 29, 29, 30, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
    29, 29, 29, 29, 29, 29, 29,  0, 29, 29, 29, 29, 29, 29, 29, 29, 
    29, 29, 29, 30, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
    29, 29, 29, 29, 29, 29, 29,  0, 29, 29, 29, 29, 29, 29, 29, 29
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\12\2\1\1\1\0\11\2\1\10\2\2\3\11\4\12"+
    "\3\13\3\14\4\2\3\15\3\16\3\17\3\20\3\21"+
    "\1\2\3\22\3\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\37\0\76\0\37\0\37\0\135\0\37"+
    "\0\174\0\233\0\272\0\331\0\370\0\u0117\0\u0136\0\u0155"+
    "\0\u0174\0\u0193\0\u01b2\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d"+
    "\0\u026c\0\u028b\0\u02aa\0\u02c9\0\u02e8\0\174\0\u0307\0\u0326"+
    "\0\u0345\0\u020f\0\u0364\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff"+
    "\0\u024d\0\u041e\0\u043d\0\u026c\0\u045c\0\u047b\0\u049a\0\u04b9"+
    "\0\u04d8\0\u04f7\0\u0307\0\u0516\0\u0535\0\u0326\0\u0554\0\u0573"+
    "\0\u03c1\0\u0592\0\u05b1\0\u047b\0\u05d0\0\u05ef\0\u049a\0\u060e"+
    "\0\u062d\0\u064c\0\u04d8\0\u066b\0\u068a\0\u062d\0\u06a9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\2\3\11\1\15\1\16\1\11\1\20"+
    "\1\21\1\22\2\2\1\23\45\0\1\4\1\0\24\4"+
    "\11\0\1\7\40\0\12\11\1\0\11\11\2\0\1\24"+
    "\10\0\12\11\1\0\2\11\1\25\6\11\2\0\1\24"+
    "\10\0\12\11\1\0\2\11\1\26\1\11\1\27\4\11"+
    "\2\0\1\24\10\0\12\11\1\0\1\30\1\31\7\11"+
    "\2\0\1\24\10\0\12\11\1\0\4\11\1\32\4\11"+
    "\2\0\1\24\10\0\12\11\1\0\2\11\1\33\6\11"+
    "\2\0\1\24\10\0\12\11\1\0\7\11\1\34\1\11"+
    "\2\0\1\24\10\0\12\11\1\0\5\11\1\35\3\11"+
    "\2\0\1\24\10\0\3\11\1\36\6\11\1\0\11\11"+
    "\2\0\1\24\10\0\12\11\1\0\1\11\1\37\7\11"+
    "\2\0\1\24\34\0\1\3\36\0\1\11\12\0\12\11"+
    "\1\0\3\11\1\40\5\11\2\0\1\24\6\0\1\41"+
    "\1\0\12\42\1\41\11\42\1\0\1\41\1\43\6\0"+
    "\1\44\1\0\12\45\1\44\2\45\1\46\6\45\1\0"+
    "\1\44\1\47\6\0\1\50\1\0\12\51\1\50\11\51"+
    "\1\0\1\50\1\52\6\0\1\53\1\0\12\54\1\53"+
    "\11\54\1\0\1\53\1\55\10\0\12\11\1\0\10\11"+
    "\1\56\2\0\1\24\10\0\12\11\1\0\6\11\1\57"+
    "\2\11\2\0\1\24\10\0\12\11\1\0\1\60\10\11"+
    "\2\0\1\24\10\0\12\11\1\0\1\11\1\61\7\11"+
    "\2\0\1\24\6\0\1\62\1\0\12\63\1\62\11\63"+
    "\1\0\1\62\1\64\6\0\1\65\1\0\12\66\1\65"+
    "\11\66\1\0\1\65\1\67\6\0\1\41\1\0\24\41"+
    "\1\0\2\41\6\0\1\41\1\0\24\41\1\11\2\41"+
    "\6\0\1\44\1\0\24\44\1\0\2\44\6\0\1\44"+
    "\1\0\12\45\1\44\11\45\1\0\1\44\1\47\6\0"+
    "\1\70\1\0\12\71\1\70\11\71\1\0\1\70\1\72"+
    "\6\0\1\44\1\0\24\44\1\11\2\44\6\0\1\50"+
    "\1\0\24\50\1\0\2\50\6\0\1\50\1\0\24\50"+
    "\1\11\2\50\6\0\1\53\1\0\24\53\1\0\2\53"+
    "\6\0\1\53\1\0\24\53\1\11\2\53\6\0\1\73"+
    "\1\0\12\74\1\73\11\74\1\0\1\73\1\75\6\0"+
    "\1\76\1\0\12\77\1\76\11\77\1\0\1\76\1\100"+
    "\10\0\12\11\1\0\6\11\1\101\2\11\2\0\1\24"+
    "\6\0\1\102\1\0\12\103\1\102\11\103\1\0\1\102"+
    "\1\104\6\0\1\62\1\0\24\62\1\0\2\62\6\0"+
    "\1\62\1\0\24\62\1\11\2\62\6\0\1\65\1\0"+
    "\24\65\1\0\2\65\6\0\1\65\1\0\24\65\1\11"+
    "\2\65\6\0\1\70\1\0\24\70\1\0\2\70\6\0"+
    "\1\70\1\0\24\70\1\11\2\70\6\0\1\73\1\0"+
    "\24\73\1\0\2\73\6\0\1\73\1\0\24\73\1\11"+
    "\2\73\6\0\1\76\1\0\24\76\1\0\2\76\6\0"+
    "\1\76\1\0\24\76\1\11\2\76\6\0\1\105\1\0"+
    "\12\106\1\105\11\106\1\0\1\105\1\107\6\0\1\102"+
    "\1\0\24\102\1\0\2\102\6\0\1\102\1\0\24\102"+
    "\1\11\2\102\6\0\1\105\1\0\24\105\1\0\2\105"+
    "\6\0\1\105\1\0\24\105\1\11\2\105";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1736];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\1\1\1\11\13\1\1\0"+
    "\63\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(Tokens.EOF,new String("Fim do arquivo"));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Caracter ilegal: " + yytext());
            }
            // fall through
          case 20: break;
          case 2:
            { 
            }
            // fall through
          case 21: break;
          case 3:
            { return new Symbol(Tokens.ID, yytext());
            }
            // fall through
          case 22: break;
          case 4:
            { return new Symbol(Tokens.LPAREN, yytext());
            }
            // fall through
          case 23: break;
          case 5:
            { return new Symbol(Tokens.RPAREN, yytext());
            }
            // fall through
          case 24: break;
          case 6:
            { return new Symbol(Tokens.NUMERO, new Integer(yytext()));
            }
            // fall through
          case 25: break;
          case 7:
            { return new Symbol(Tokens.SEMI, yytext());
            }
            // fall through
          case 26: break;
          case 8:
            { return new Symbol(Tokens.UM, yytext());
            }
            // fall through
          case 27: break;
          case 9:
            { return new Symbol(Tokens.DIVIDIDO, yytext());
            }
            // fall through
          case 28: break;
          case 10:
            { return new Symbol(Tokens.DOBRO, yytext());
            }
            // fall through
          case 29: break;
          case 11:
            { return new Symbol(Tokens.SOMA, yytext());
            }
            // fall through
          case 30: break;
          case 12:
            { return new Symbol(Tokens.MENOS, yytext());
            }
            // fall through
          case 31: break;
          case 13:
            { return new Symbol(Tokens.VEZES, yytext());
            }
            // fall through
          case 32: break;
          case 14:
            { return new Symbol(Tokens.CINCO, yytext());
            }
            // fall through
          case 33: break;
          case 15:
            { return new Symbol(Tokens.DOIS, yytext());
            }
            // fall through
          case 34: break;
          case 16:
            { return new Symbol(Tokens.NOVE, yytext());
            }
            // fall through
          case 35: break;
          case 17:
            { return new Symbol(Tokens.OITO, yytext());
            }
            // fall through
          case 36: break;
          case 18:
            { return new Symbol(Tokens.TRES, yytext());
            }
            // fall through
          case 37: break;
          case 19:
            { return new Symbol(Tokens.QUATRO, yytext());
            }
            // fall through
          case 38: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
